inherit_gem:
  ezcater_rubocop: conf/rubocop_gem.yml

inherit_mode:
  merge:
  - Exclude

plugins:
  - rubocop-capybara

RSpec/ExampleLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/*'
