version: "3.4"
volumes:
  bundle-volume:
  shared-volume:
x-environment: &default-environment
  PRYRC: /usr/src/app/.docker-pryrc
  BUNDLE_IGNORE_CONFIG: 1
  BUNDLE_DISABLE_SHARED_GEMS: "true"
  ZEEBE_ADDRESS: zeebe-bpmn-gateway:26500
x-service: &default-service
  image: ruby:2.6.6
  volumes:
    - .:/usr/src/gem
    - ./compose/entrypoint.sh:/tmp/entrypoint.sh
    - bundle-volume:/usr/local/bundle:delegated
    - shared-volume:/usr/src/shared:delegated
  tty: true
  stdin_open: true
services:
  zeebe:
    image: camunda/zeebe:0.23.2
    environment:
      ZEEBE_LOG_LEVEL: debug
    volumes:
      - ./compose/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./compose/application.yml:/usr/local/zeebe/config/application.yaml

  monitor:
    image: camunda/zeebe-simple-monitor:0.19.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe-bpmn-gateway:26500
      - zeebe.client.worker.hazelcast.connection=zeebe-bpmn-gateway:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe

  console:
    <<: *default-service
    environment:
      <<: *default-environment
    entrypoint: /tmp/entrypoint.sh
    command: bash
    working_dir: /usr/src/gem
    depends_on:
      - zeebe
