version: "3.4"
volumes:
  bundle-volume:
  shared-volume:
x-environment: &default-environment
  PRYRC: /usr/src/app/.docker-pryrc
  BUNDLE_IGNORE_CONFIG: 1
  BUNDLE_DISABLE_SHARED_GEMS: "true"
  ZEEBE_ADDRESS: zeebe-bpmn-gateway:26500
x-service: &default-service
  build:
    context: .
  volumes:
    - .:/usr/src/gem
    - bundle-volume:/usr/local/bundle:delegated
    - shared-volume:/usr/src/shared:delegated
  tty: true
  stdin_open: true
services:
  zeebe-bpmn-gateway:
    container_name: zeebe-bpmn-gateway_1
    image: camunda/zeebe:0.23.2
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      ZEEBE_LOG_LEVEL: debug
    volumes:
      - ./compose/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./compose/application.yml:/usr/local/zeebe/config/application.yaml

  zeebe-bpmn-monitor:
    container_name: zeebe-bpmn-monitor_1
    image: camunda/zeebe-simple-monitor:0.19.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe-bpmn-gateway:26500
      - zeebe.client.worker.hazelcast.connection=zeebe-bpmn-gateway:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe-bpmn-gateway

  zeebe-bpmn-console:
    <<: *default-service
    container_name: zeebe-bpmn-console_1
    environment:
      <<: *default-environment
    command: bash
    depends_on:
      - zeebe-bpmn-gateway
