version: "3.4"
volumes:
  bundle-volume:
  shared-volume:
x-environment: &default-environment
  PRYRC: /usr/src/app/.docker-pryrc
  BUNDLE_IGNORE_CONFIG: 1
  BUNDLE_DISABLE_SHARED_GEMS: "true"
  ZEEBE_ADDRESS: zeebe:26500
x-service: &default-service
  image: ruby:2.7.3
  volumes:
    - .:/usr/src/gem
    - ./compose/entrypoint.sh:/tmp/entrypoint.sh
    - bundle-volume:/usr/local/bundle:delegated
    - shared-volume:/usr/src/shared:delegated
  tty: true
  stdin_open: true
services:
  zeebe:
    image: camunda/zeebe:${ZEEBE_VERSION:-1.0.0}
    environment:
      ZEEBE_LOG_LEVEL: debug

  console:
    <<: *default-service
    environment:
      <<: *default-environment
    entrypoint: /tmp/entrypoint.sh
    command: bash
    working_dir: /usr/src/gem
    depends_on:
      - zeebe
